kadai/config/routes.rb
Rails.application.routes.draw do
root to:'home#top' # ここを追記します
get 'home/about', to: 'home#about'
devise_for :users
resources :users
resources :books
# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

kadai/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

kadai/app/models/book.rb
class Book < ApplicationRecord
    belongs_to :user
end

kadai/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
    attachment :profile_image
    has_many :books, dependent: :destroy
    
    validates :name, uniqueness: true, presence: true, length: {minimum: 2, maximum: 20}
    validates :introduction, length: { maximum: 200 }
end

kadai/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  def after_sign_in_path_for(resource)
    user_path(resource)
  end
  
    def after_sign_up_path_for(resource)
    user_path(resource)
    end

before_action :user_permitted_parameters, if: :devise_controller?

protected
 def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys[:name])
      devise_parameter_sanitizer.permit(:sign_in, keys[:name])
 end

end

kadai/app/controllers/books_controller.rb
class BooksController < ApplicationController
def index
  @books = Book.all
  @book = Book.new
end
  
def create
  @book = Book.new(book_params)
  if  @book.save
    flash[:notice] = "Book was successfully created."
    redirect_to book_path(@book.id)
    
  else
    @books = Book.all
     render :index
  end
end

  def show
      @booknew = Book.new    
      @book = Book.find(params[:id])
      
  end

  def edit
    @book = Book.find(params[:id])
  end
  
  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end
  
  def update
    @book = Book.find(params[:id])
    @book.update(book_params)
    flash[:notice] = "Book was successfully created."
    redirect_to book_path(@book.id)
  end

private
    def book_params
      params.require(:book).permit(:title, :body, :name)
    end
end

kadai/app/controllers/home_controller.rb
class HomeController < ApplicationController
  def top
  end

  def about
  end
end

kadai/app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

kadai/app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

kadai/app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

kadai/app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

kadai/app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

kadai/app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

kadai/app/controllers/users_controller.rb
class UsersController < ApplicationController
before_action :authenticate_user!
    def index
      @users = User.all
    end
    
    def new 
    end

    def edit
      @user = User.find(params[:id])
    end

  def show
    @user = User.find(params[:id])
    @book = Book.new
  end

  def create_book
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    @book.save
    redirect_to user_path(current_user.id)

  end
  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    redirect_to user_path(@user.id)
  end


  private
  def book_params
    params.require(:book).permit(:title, :body)
  end
  
  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end

end

kadai/app/helpers/application_helper.rb
module ApplicationHelper
end

kadai/app/helpers/books_helper.rb
module BooksHelper
end

kadai/app/helpers/home_helper.rb
module HomeHelper
end

kadai/app/helpers/users_helper.rb
module UsersHelper
end

kadai/app/views/books/_newbook.html.erb
<h3>New book</h3>
          <%= form_for book do |f| %>
            <div class=“book-form”>
              <label for=“book_title”><h4>Title</h4></label>
              <%= f.text_field :title %>
            </div>
            <div class=“book-form”>
              <label for=“book_body”><h4>Opinion</h4></label>
              <%= f.text_area :body %>
            </div>
            <div class=“row”>
              <%= f.submit 'Create Book'%>
            </div>
          <% end %>

kadai/app/views/books/index.html.erb
  <div class="row">
    <div class="col-xs-3"> 
              <%= render 'users/userinfo', user: @user %> 
              <%= render 'books/newbook', book: @book %>
    </div>
    <div class="col-xs-9">
           <table class="table table-hover table-inverse">
             <thead>
              <tr>
                 <th></th>
                 <th><h4>Title</h4></th>
                 <th><h4>Opinion</h4></th>
              </tr>
             </thead>
             <% @user.books.each do |book| %>
             <tbody>
              <tr>
                <td><%= attachment_image_tag @user, :profile_image, :fill, 40, 40, format: 'jpeg', class: "img-circle pull-left profile-img"%></td>
                <td><%= @book.title %></td>
                <td><%= @book.body %></td>
              </tr>
            </tbody>
            <% end %>
      </table>
    </div>
</div>

kadai/app/views/home/about.html.erb
  	<div class='body'>
      <div class='container'>

        <p id="notice"></p>


      	<h1>Welcome to <span class='glyphicon glyphicon-book'></span><strong>Bookers</strong>!</h1>


      </div>
    </div>

    <footer>
  <div class='container'>
  	<div class='row'>
    	<div class='col-xs-3 col-xs-offset-9'>
    		<p>CopyRight Infratop.inc</p>
    	</div>
    </div>
  </div>

kadai/app/views/home/top.html.erb
<div class ="container">
 <div class='top-message col-md-offset-3 col-md-6'>
    <h1>welcome to <span class='glyphicon glyphicon-book'><strong>Bookers</strong>  !!</h1>
          <p>In  <span class='glyphicon glyphicon-book'></span><strong>Bookers</strong>, </p>
          <p>you can share and exchange  your opinions , inpressions , and emotions</p>
          <p> about various books!</p>
         <%= link_to 'log in', new_user_session_path ,class:'btn btn-info col-xs-10 col-xs-offset-1 sign_in' %>
         <%= link_to 'Sign up', new_user_registration_path ,class:'btn btn-success col-xs-10 col-xs-offset-1 sign_up' %>

 </div>
</div>

kadai/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width,initial-scale=1">
  </head>

  <body>
    <div>
    <header class="navbar navbar-inverse">
          <nav class='nav navbar-nav navbar-left' >
            <span>Bookers</span>
          </nav>
            <ul class="nav navbar-nav navbar-right">
              <% if user_signed_in? %>
          <nav>
                <li class="glyphicon glyphicon-home home"><%= link_to "Home", user_path(current_user.id) %></li>
                <li class="glyphicon glyphicon-link about"><%= link_to "User", users_path %></li>
                <li class="glyphicon glyphicon-edit sign_up"><%= link_to "Books", books_path %></li>
                <li class="glyphicon glyphicon-log-in sign_in"><%= link_to "log out", destroy_user_session_path, method: :delete %></li>
          </nav>
            <% else %>
            <nav>
                <li class="glyphicon glyphicon-home home"><%= link_to "Home", root_path %></li>
                <li class="glyphicon glyphicon-user users"><%= link_to "about", home_about_path %></li>
                <li class="glyphicon glyphicon-book books"><%= link_to "Log in", new_user_session_path %></li>
                <li class="glyphicon glyphicon-log-out logout"><%= link_to "Sign up", new_user_registration_path %></li>
                </ul>
            </nav>
        <% end %>
      </header>
      </div>
<%= yield %>
  </body>
</html>

kadai/app/views/users/_userinfo.html.erb
<h3>User info</h3>

<table>
  <tr>
    <td><%= attachment_image_tag @user, :profile_image, :fill, 100, 100, format: 'jpeg', class: "img-circle pull-left profile-img"%></td>
  </tr>
  <tr>
  　　  <td>name</td>
    　<td><%= user.name %></td>
  </tr>
  <tr>
  　　  <td>introduction</td>
  　　<td><%= user.introduction %></td>
  </tr>
  <tr>
  　　<td><% if user.id == current_user.id %></td>
    <td><p><%= link_to "プロフィール編集", edit_user_path(user), class: "pull-right" %></p></td>
  </tr>
    <% end %>
  </table>
</div>

kadai/app/views/users/edit.html.erb
<h2 class="header-space">User info</h2>

<%= form_for(@user) do |f| %>

  <div class="field">
    <%= f.label :Name %><br/>
    <%= f.text_field :name, autofocus: true, autocomplete: "name" %>
  </div>

  <div class="form-group has-icon user-edit">
    <%= f.label :Image %><br/>
    <%= f.attachment_field :profile_image, placeholder: "Image", class: "user-edit-form" %>
  </div>

  <div class="field user-edit">
    <%= f.label :Introduction %><br/>
    <%= f.text_area :introduction, autofocus: true, autocomplete: "introduction" %>
  </div>

  <div class="actions">
    <%= f.submit "Update" %>
  </div>

<% end %>

kadai/app/views/users/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-3"> 
              <%= render 'users/userinfo', user: @user %> 
              <%= render 'books/newbook', book: @book %>
    </div>
    <div class="col-xs-9">
           <table class="table table-hover table-inverse">
             <thead>
              <tr>
                 <th></th>
                 <th><h4>Title</h4></th>
                 <th><h4>Opinion</h4></th>
              </tr>
             </thead>
             <% @user.users.each do |user| %>
             <tbody>
              <tr>
                <td><%= attachment_image_tag @user, :profile_image, :fill, 40, 40, format: 'jpeg', class: "img-circle pull-left profile-img"%></td>
                <td><%= <%= @user.name %> %></td>
                <td><% link_to('Show', user_path(current_user.id)) %></td>
              </tr>
            </tbody>
            <% end %>
      </table>
    </div>
</div>

kadai/app/views/users/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-3"> 
              <%= render 'users/userinfo', user: @user %> 
              <%= render 'books/newbook', book: @book %>
    </div>
    <div class="col-xs-9">
           <table class="table table-hover table-inverse">
             <thead>
              <tr>
                 <th></th>
                 <th><h4>Title</h4></th>
                 <th><h4>Opinion</h4></th>
              </tr>
             </thead>
        <% @user.books.each do |book| %>     
             <tbody>
              <tr>
                <td><%= attachment_image_tag @user, :profile_image, :fill, 40, 40, format: 'jpeg', class: "img-circle pull-left profile-img"%></td>
                <td><%= @book.title %></td>
                <td><%= @book.body %></td>
              </tr>
            </tbody>
        <% end %>
      </table>
    </div>
</div>